-- Category rules for the eBay sync, widened from the original nine-keyword
-- seed after importing the real 90-listing catalogue: the shop is recognised
-- by brand (Christophe Robin, Scottish Fine Soaps, Bestway, Makita...) as much
-- as by product noun. Replaces all keyword rules; safe to re-run.
DELETE FROM ebay_category_map WHERE match_type = 'keyword';
WITH rule(word, cat, priority) AS (
  VALUES
  ('dry dog food','pet-food-treats',120),
  ('dog food','pet-food-treats',115),
  ('cat food','pet-food-treats',115),
  ('lily''s kitchen','pet-food-treats',110),
  ('dreamies','pet-food-treats',110),
  ('catisfactions','pet-food-treats',110),
  ('dentastix','pet-food-treats',110),
  ('kitten','pet-food-treats',90),
  ('puppy','pet-food-treats',90),
  ('dog','pet-food-treats',80),
  ('cat','pet-food-treats',70),
  ('pet','pet-food-treats',50),
  ('pet food','pet-food-treats',115),
  ('barbie','toys-games',118),
  ('plushie','toys-games',115),
  ('animagic','toys-games',118),
  ('doll','toys-games',110),
  ('pokemon','toys-games',115),
  ('pokémon','toys-games',115),
  ('funko','toys-games',115),
  ('catan','toys-games',115),
  ('vtech','toys-games',115),
  ('paw patrol','toys-games',110),
  ('board game','toys-games',100),
  ('trading card','toys-games',100),
  ('lego','toys-games',100),
  ('jigsaw','toys-games',90),
  ('puzzle','toys-games',80),
  ('toy','toys-games',60),
  ('dolce gusto','coffee-tea',115),
  ('nespresso','coffee-tea',115),
  ('coffee','coffee-tea',110),
  ('pukka','coffee-tea',110),
  ('clipper','coffee-tea',105),
  ('tea bags','coffee-tea',110),
  ('herbal tea','coffee-tea',105),
  ('organic tea','coffee-tea',105),
  ('espresso','coffee-tea',100),
  ('latte','coffee-tea',95),
  ('tea,','coffee-tea',90),
  ('infusion','coffee-tea',85),
  ('christophe robin','hair-beauty',120),
  ('scottish fine soaps','hair-beauty',120),
  ('sottish fine soaps','hair-beauty',120),
  ('wella','hair-beauty',115),
  ('maybelline','hair-beauty',115),
  ('shiseido','hair-beauty',115),
  ('nuxe','hair-beauty',115),
  ('burt''s bees','hair-beauty',115),
  ('vaseline','hair-beauty',115),
  ('framar','hair-beauty',115),
  ('scholl','hair-beauty',110),
  ('compeed','hair-beauty',105),
  ('tsubaki','hair-beauty',110),
  ('shampoo','hair-beauty',110),
  ('conditioner','hair-beauty',105),
  ('hair oil','hair-beauty',110),
  ('hair mask','hair-beauty',110),
  ('hairbrush','hair-beauty',110),
  ('hair &','hair-beauty',100),
  ('mascara','hair-beauty',110),
  ('lip balm','hair-beauty',110),
  ('lip serum','hair-beauty',110),
  ('hand wash','hair-beauty',105),
  ('body wash','hair-beauty',105),
  ('hand and nail','hair-beauty',105),
  ('body lotion','hair-beauty',105),
  ('eau de parfum','hair-beauty',110),
  ('perfume','hair-beauty',100),
  ('razor','hair-beauty',95),
  ('shower gel','hair-beauty',95),
  ('foot file','hair-beauty',105),
  ('curl defining','hair-beauty',105),
  ('tint brush','hair-beauty',105),
  ('toblerone','snacks-sweets',115),
  ('cadbury','snacks-sweets',115),
  ('haribo','snacks-sweets',110),
  ('chocolate','snacks-sweets',105),
  ('crisps','snacks-sweets',105),
  ('sweets','snacks-sweets',100),
  ('lozenge','snacks-sweets',60),
  ('protein bar','breakfast-bars',115),
  ('kind protein','breakfast-bars',115),
  ('cereal bar','breakfast-bars',110),
  ('granola','breakfast-bars',100),
  ('porridge','breakfast-bars',100),
  ('cereal','breakfast-bars',90),
  ('milwaukee','diy-tools',115),
  ('loctite','diy-tools',115),
  ('gorilla','diy-tools',115),
  ('super glue','diy-tools',110),
  ('socket adaptor','diy-tools',110),
  ('drill','diy-tools',105),
  ('screwdriver','diy-tools',100),
  ('tape','diy-tools',95),
  ('paint','diy-tools',80),
  ('tool','diy-tools',70),
  ('bestway','garden',115),
  ('pool cover','garden',115),
  ('swimming float','garden',110),
  ('above ground pool','garden',115),
  ('bbq','garden',115),
  ('weedkiller','garden',115),
  ('strimmer','garden',115),
  ('trimmer cord','garden',110),
  ('makita','garden',105),
  ('filter pump','garden',105),
  ('garden','garden',100),
  ('seeds','garden',95),
  ('hose','garden',90),
  ('kenwood','household-appliances',115),
  ('gtech','household-appliances',115),
  ('food processor','household-appliances',115),
  ('floor sweeper','household-appliances',115),
  ('kettle','household-appliances',110),
  ('toaster','household-appliances',110),
  ('air fryer','household-appliances',110),
  ('vacuum','household-appliances',105),
  ('silentnight','home-living',115),
  ('woodwick','home-living',115),
  ('glade','home-living',115),
  ('airwick','home-living',115),
  ('air freshener','home-living',110),
  ('scented candle','home-living',110),
  ('mattress topper','home-living',115),
  ('duvet','home-living',115),
  ('tumbler','home-living',110),
  ('quencher','home-living',110),
  ('room spray','home-living',105),
  ('graphics card','electronics',120),
  ('nvidia','electronics',115),
  ('geforce','electronics',115),
  ('msi','electronics',110),
  ('ink catridge','electronics',115),
  ('ink cartridge','electronics',115),
  ('canon','electronics',110)
)
INSERT INTO ebay_category_map (match_type, match_value, category_id, priority)
SELECT 'keyword', rule.word, c.id, rule.priority
FROM rule JOIN categories c ON c.slug = rule.cat;
